name: Build IPTV (EPG Sync & Live Event)

on:
  # Jalan otomatis jika ada perubahan file penting
  push:
    branches:
      - main
    paths:
      - "scripts/**"
      - "live_epg_sports.m3u"
      - "requirements.txt"

  # Jalan otomatis setiap 6 jam
  schedule:
    - cron: "0 */6 * * *"

  # Bisa dijalankan manual
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build M3U (EPG + Live Event)
        run: python scripts/build_all.py

      - name: Commit result if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add live_all.m3u

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto update M3U (EPG sync & live event)"
            git push
          fi
